backend:
  name: github
  repo: SEU_USUARIO/SEU_REPOSITORIO # NÃO ESQUEÇA DE AJUSTAR ISSO DEPOIS!
  branch: main 

local_backend: true # SEMPRE SEM INDENTAÇÃO

# Configurações de Mídia (Sem Indentação)
media_folder: 'static/img' 
public_folder: '/static/img' 

# Fluxo Editorial (Sem Indentação)
publish_mode: editorial_workflow 

collections:
  - name: 'veiculos' 
    label: 'Anúncios de Veículos'
    folder: 'data'
    extension: 'json'
    format: 'json'
    create: true 
    delete: true 
    slug: '{{modelo}}' 
    
    fields: 
      - {label: 'Modelo do Veículo', name: 'modelo', widget: 'string', required: true}
      - {label: 'Valor', name: 'valor', widget: 'string', pattern: ['^R\$ [0-9]{1,3}(\.[0-9]{3})*(\,[0-9]{2})?$', 'Ex: R$ 50.000,00'], hint: 'Sempre no formato "R$ X.XXX,XX"'}
      - {label: 'URL da Foto', name: 'foto_url', widget: 'image', required: true} 
      - {label: 'Ativo para Kiosk?', name: 'ativo', widget: 'boolean', default: true, hint: 'Desmarque para ocultar o carro do carrossel.'}